#!/usr/bin/env python3
"""Generate a randomized self-checking testbench for fp32_mul / fp32_add.

Three hand-picked cases were enough to catch one real bug in fp32_add (the
normalize path and the carry path disagreed by one bit), which is exactly why
three cases are not enough to trust it.  This emits N random vectors checked
against IEEE-754 binary32 arithmetic computed in Python with struct, so the
comparison is bit-exact rather than approximate.

Operands are drawn from the magnitude range a raytracer actually produces, and
deliberately include cancelling subtractions - the case that exercises the long
left-shift in the adder's normalize stage, where the original bug lived.

    python3 hw/raytrace_mac/gen_fp_vectors.py 300 > tb_fp_random.v
    iverilog -g2012 -o tb_fp tb_fp_random.v fp32_units.v && vvp tb_fp
"""

import random
import struct
import sys


def f32(x):
    """Round a Python float to binary32."""
    return struct.unpack('>f', struct.pack('>f', x))[0]


def bits(x):
    return struct.unpack('>I', struct.pack('>f', f32(x)))[0]


def is_normal(x):
    b = bits(x)
    e = (b >> 23) & 0xFF
    return 0 < e < 0xFF


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 300
    random.seed(20260913)

    cases = []
    while len(cases) < n:
        kind = random.random()
        if kind < 0.25:
            # same-magnitude pair -> cancelling subtraction (long normalize)
            a = f32(random.uniform(-100, 100))
            b = f32(a * f32(1.0 + random.uniform(-1e-3, 1e-3)))
            b = f32(-b)
        elif kind < 0.5:
            a = f32(random.uniform(-1e3, 1e3))
            b = f32(random.uniform(-1e3, 1e3))
        elif kind < 0.75:
            a = f32(random.uniform(-1, 1))
            b = f32(random.uniform(-1, 1))
        else:
            a = f32(random.uniform(-1e5, 1e5))
            b = f32(random.uniform(-1e-3, 1e-3))

        s = f32(a + b)
        p = f32(a * b)
        # Skip anything that leaves the normal range: the units flush
        # subnormals and saturate, which is documented, not a defect.
        if not all(is_normal(v) or v == 0.0 for v in (a, b, s, p)):
            continue
        if s == 0.0 or p == 0.0 or a == 0.0 or b == 0.0:
            continue
        cases.append((a, b, s, p))

    out = []
    w = out.append
    w("// GENERATED by gen_fp_vectors.py - do not edit by hand.")
    w("// %d randomized binary32 vectors checked against Python struct." % n)
    w("`timescale 1ns/1ps")
    w("module tb_fp_random;")
    w("    reg clk = 1'b0; reg rst_n = 1'b0;")
    w("    always #5 clk = ~clk;")
    w("    integer errors = 0; integer checked = 0;")
    w("    reg [31:0] A [0:%d]; reg [31:0] B [0:%d];" % (n - 1, n - 1))
    w("    reg [31:0] S [0:%d]; reg [31:0] P [0:%d];" % (n - 1, n - 1))
    w("    reg [31:0] a_r = 0, b_r = 0;")
    w("    wire [31:0] mul_y, add_y; wire mul_v, add_v;")
    w("    fp32_mul u_mul (.clk(clk), .rst_n(rst_n), .a(a_r), .b(b_r),"
      " .in_valid(1'b1), .y(mul_y), .out_valid(mul_v));")
    w("    fp32_add u_add (.clk(clk), .rst_n(rst_n), .a(a_r), .b(b_r),"
      " .in_valid(1'b1), .y(add_y), .out_valid(add_v));")
    w("    integer i;")
    w("    initial begin")
    for i, (a, b, s, p) in enumerate(cases):
        w("        A[%d]=32'h%08X; B[%d]=32'h%08X; S[%d]=32'h%08X; P[%d]=32'h%08X;"
          % (i, bits(a), i, bits(b), i, bits(s), i, bits(p)))
    w("        repeat (3) @(negedge clk); rst_n = 1'b1;")
    w("        for (i = 0; i < %d; i = i + 1) begin" % n)
    w("            a_r = A[i]; b_r = B[i];")
    w("            repeat (3) @(negedge clk);")
    w("            checked = checked + 1;")
    w("            if (add_y !== S[i]) begin")
    w("                errors = errors + 1;")
    w("                if (errors < 8) $display(\"FAIL add #%0d: %h + %h = %h,"
      " expected %h\", i, A[i], B[i], add_y, S[i]);")
    w("            end")
    w("            if (mul_y !== P[i]) begin")
    w("                errors = errors + 1;")
    w("                if (errors < 8) $display(\"FAIL mul #%0d: %h * %h = %h,"
      " expected %h\", i, A[i], B[i], mul_y, P[i]);")
    w("            end")
    w("        end")
    w("        if (errors == 0)")
    w("            $display(\"\\nTB PASS: %0d random vectors, add and mul both"
      " bit-exact\", checked);")
    w("        else")
    w("            $display(\"\\nTB FAIL: %0d errors over %0d vectors\","
      " errors, checked);")
    w("        $finish;")
    w("    end")
    w("endmodule")
    print("\n".join(out))


if __name__ == "__main__":
    main()
